spring:
  application:
    name: morrowind-web

server:
  servlet:
    context-path: /morrowind-web
  port: 8080

logging:
  file:
    name: /logs/morrowind-web/morrowind-web.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
      max-file-size: 2048MB
